# Generated by Django 4.1.1 on 2022-12-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_total_cart_amount_profile_total_cart_items"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="total_cart_amount",),
        migrations.RemoveField(model_name="profile", name="total_cart_items",),
    ]
