# Generated by Django 4.1.1 on 2022-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_total_cart_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="total_cart_amount",
            field=models.FloatField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_cart_items",
            field=models.CharField(default=0, max_length=150),
        ),
    ]
