# Generated by Django 4.1.1 on 2022-12-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_total_cart_amount_profile_total_cart_items"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="total_cart_amount",),
        migrations.AlterField(
            model_name="profile",
            name="total_cart_items",
            field=models.IntegerField(default=0),
        ),
    ]
