# Generated by Django 4.1.1 on 2022-11-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_product_seller_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="seller_name", new_name="seller",
        ),
    ]
