# Generated by Django 4.1.1 on 2022-12-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_oderhistory"),
    ]

    operations = [
        migrations.RemoveField(model_name="oderhistory", name="user",),
        migrations.DeleteModel(name="Cart",),
        migrations.DeleteModel(name="OderHistory",),
    ]
