# Generated by Django 4.1.1 on 2022-12-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_oderhistory_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart", name="quantity", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cart", name="product_id", field=models.IntegerField(),
        ),
    ]
