# Generated by Django 4.1.1 on 2022-12-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_cart_quantity_alter_cart_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="oderhistory",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="oderhistory", name="product_id", field=models.IntegerField(),
        ),
    ]
